(*-------------------*)
(* Token definitions *)
(*-------------------*)

%token concrete terminal non_terminal

(*------------------*)
(* Axiom definition *)
(*------------------*)

%start Grammar

%%

(*--------------------*)
(* Grammar definition *)
(*--------------------*)

Grammar ::= ("%token" terminal+ ";")*
            "%start" non_terminal
            "%%" 
            Rule+
;

Rule ::= non_terminal "::=" Production ";"
;

Production ::= {Outermost_rhs "|" ...}+
;

Outermost_rhs ::= Rhs_item+ | "%empty"
;

Inner_rhs ::= Rhs_item+
;

Rhs_item ::= "(" Inner_rhs ")" Exp   
       | Word                
       | "[" Inner_rhs "]"
       | "{" Word Terminal "..." "}" Exp
;

Exp ::= "+"
     | "*"
;

Word ::= Terminal
      | non_terminal
;

Terminal ::= terminal
          | concrete
;

